<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('/','UserController@login');
Route::post('/loginPost','UserController@loginPost');
Route::get('/dashboard/view','DashboardController@view');
Route::any('/campaign/view','CampaignController@view');
Route::get('/location/view','LocationController@view');
Route::get('/device/view','DeviceController@view');
Route::any('/report/analytic','ReportController@analytic');
Route::get('/user/connectsocialaccount','UserController@connectsocialaccount');
Route::get('/subuser/viewsubuser','SubuserController@viewsubuser');
Route::get('/options/view','OptionsController@view');
Route::get('/integration/view','IntegrationController@view');
Route::get('/timeline/view','TimelineController@view');
Route::get('/dashboard/membersarea','DashboardController@membersarea');
Route::get('/user/affiliatedashboard','UserController@affiliatedashboard');
Route::get('/user/editprofile','UserController@editprofile');
Route::get('/user/logout','UserController@logout');
Route::any('/user/lockscreen','UserController@lockscreen');
Route::post('/user/lockscreenPost','UserController@lockscreenPost');
Route::any('/location/overview','LocationController@overview');
Route::post('/location/update','LocationController@update');
Route::post('/location/saveschedule','LocationController@saveschedule');
Route::post('/location/addlocationoptions','LocationController@addlocationoptions');
Route::post('/location/assignsubuser','LocationController@assignsubuser');
Route::get('/location/removeuserfromlocation','LocationController@removeuserfromlocation');
Route::get('/landingpage/viewlandingpage','LandingpageController@viewlandingpage');
Route::post('/device/update','DeviceController@update');
Route::post('/device/create','DeviceController@create');
Route::post('/campaign/delete','CampaignController@delete');
Route::post('/campaign/CloneCampaign','CampaignController@CloneCampaign');
Route::get('/report/list','ReportController@userlist');
Route::post('/user/createsocialapp','UserController@createsocialapp');
Route::post('/user/deleteapp','UserController@deleteapp');
Route::post('/subuser/delete','SubuserController@delete');
Route::post('/options/savebranding','OptionsController@savebranding');
Route::post('/integration/savegetresponseapiinformation','IntegrationController@savegetresponseapiinformation');
Route::post('/integration/saveicontactapiinformation','IntegrationController@saveicontactapiinformation');
Route::post('/integration/savemailchimpapiinformation','IntegrationController@savemailchimpapiinformation');
Route::post('/integration/savesendreachapiinformation','IntegrationController@savesendreachapiinformation');
Route::post('/integration/saveactivecampaignapiinformation','IntegrationController@saveactivecampaignapiinformation');
Route::post('/integration/deleteintegration','IntegrationController@deleteintegration');
Route::any('/admintools/activitylog','AdminController@activitylog');
Route::any('/admintools/modifyuser','AdminController@modifyuser');
Route::get('/overview/view','OverviewController@view');
Route::post('/overview/deleteuser','OverviewController@deleteuser');
Route::any('/user/forgotpassword','UserController@forgotpassword');
Route::any('/user/resetpassword','UserController@resetpassword');
Route::post('/location/delete','LocationController@delete');
Route::post('/location/create','LocationController@create');
Route::post('/ajax/GetSocialUserDetail','AjaxController@GetSocialUserDetail');


/*****       AJAX REQUEST           *****/
Route::post('/ajax/uploadcampaignbackgroundimage','AjaxController@uploadcampaignbackgroundimage');
Route::post('/ajax/DeleteCBGImage','AjaxController@DeleteCBGImage');
Route::post('/ajax/GetAllCampaigns','AjaxController@GetAllCampaigns');
Route::post('/ajax/GetLanguageDetails','AjaxController@GetLanguageDetails');
Route::post('/ajax/RetrieveCampaignById','AjaxController@RetrieveCampaignById');
Route::post('/ajax/CheckFacebookPage','AjaxController@CheckFacebookPage');
Route::post('ajax/GetAutoresponderList','AjaxController@GetAutoresponderList');
Route::post('/ajax/CloneCampaign','AjaxController@CloneCampaign');
Route::post('/ajax/GetAllLocations','AjaxController@GetAllLocations');
Route::post('ajax/GetAllDevices','AjaxController@GetAllDevices');
Route::any('/ajax/GenerateOverview','AjaxController@GenerateOverview');
Route::post('/ajax/Logoutuseraftersessiontimeout','AjaxController@Logoutuseraftersessiontimeout');
Route::post('/ajax/SetAsDefaultCampaign','AjaxController@SetAsDefaultCampaign');
Route::post('/ajax/GetScheduleById','AjaxController@GetScheduleById');
Route::post('/ajax/DeleteSchedule','AjaxController@DeleteSchedule');
Route::post('/ajax/AssignDevice','AjaxController@AssignDevice');
Route::post('/ajax/RemovingDevice','AjaxController@RemovingDevice');
Route::post('/ajax/EditDevice','AjaxController@EditDevice');
Route::post('/ajax/SaveSubUser','AjaxController@SaveSubuser');
Route::post('/ajax/CheckEmailExist','AjaxController@CheckEmailExist');
Route::post('/ajax/ChangeStatusDevice','AjaxController@ChangeStatusDevice');
Route::get('/ajax/GetSocialUsers','AjaxController@GetSocialUsers');
Route::post('/ajax/LoadTimelineData','AjaxController@LoadTimelineData');
Route::post('/ajax/RetriveAppInfoById','AjaxController@RetriveAppInfoById');
Route::post('ajax/CheckFacebookApp','AjaxController@CheckFacebookApp');
Route::post('ajax/CheckTwitterApp','AjaxController@CheckTwitterApp');
Route::post('ajax/CheckLinkedInApp','AjaxController@CheckLinkedInApp');
Route::post('ajax/CheckGoogleApp','AjaxController@CheckGoogleApp');
Route::post('ajax/CheckInstagramApp','AjaxController@CheckInstagramApp');
Route::post('ajax/CheckVkontakteApp','AjaxController@CheckVkontakteApp');
Route::post('/ajax/SetDefault','AjaxController@SetDefault');
Route::post('/ajax/GetSubUserById','AjaxController@GetSubUserById');
Route::post('/ajax/UpdateProfile','AjaxController@updateprofile');
Route::post('/ajax/GetPlatformUserProfile','AjaxController@GetPlatformUserProfile');
Route::post('/ajax/UpdateUserProfile','AjaxController@UpdateUserProfile');
Route::post('/ajax/ChangeStatusLocation','AjaxController@ChangeStatusLocation');
Route::post('/ajax/ProcessPayment','AjaxController@ProcessPayment');
Route::post('/ajax/DeletePicture','AjaxController@DeletePicture');
Route::post('/ajax/DeleteCBGImage','AjaxController@DeleteCBGImage');
Route::post('/ajax/ResetAllStatistics','AjaxController@ResetAllStatistics');
Route::post('/ajax/loadreportdata','AjaxController@loadreportdata');

Route::get('/ajax/editorsimageupload','AjaxController@editorsimageupload');
Route::get('/ajax/editorsmedia','AjaxController@editorsmedia');
Route::get('/ajax/editorsimgdel','AjaxController@editorsimgdel');